on:

push:

branches:

- main

pull_request:

types: [opened, synchronize, reopened]

name: Main Workflow

jobs:

sonarcloud:

runs-on: ubuntu-latest

steps:

- uses: actions/checkout@v2

with:

fetch-depth: 0

- name: Get Main

run: git fetch origin main

- name: Install dependencies

run: yarn

- name: Install Jest globally

run: sudo yarn add -g jest

- name: Run Tests

run: yarn test

- name: SonarCloud Scan

uses: sonarsource/sonarcloud-github-action@master

env:

GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}